load("//tools/lint:lint.bzl", "add_lint_tests")
load(
    "//tools/performance:defs.bzl",
    "drake_cc_googlebench_binary",
    "drake_py_experiment_binary",
)
load("//tools/skylark:drake_cc.bzl", "drake_cc_library")

package(default_visibility = ["//visibility:public"])

drake_cc_googlebench_binary(
    name = "benchmark_mathematical_program",
    srcs = ["benchmark_mathematical_program.cc"],
    deps = [
        "//common:add_text_logging_gflags",
        "//solvers:mathematical_program",
        "//tools/performance:fixture_common",
        "//tools/performance:gflags_main",
    ],
    add_test_rule = True,
    test_rule_timeout = "moderate",
)

drake_py_experiment_binary(
    name = "mathematical_program_experiment",
    googlebench_binary = ":benchmark_mathematical_program",
)

drake_cc_googlebench_binary(
    name = "benchmark_ipopt_solver",
    srcs = ["benchmark_ipopt_solver.cc"],
    deps = [
        "//common:add_text_logging_gflags",
        "//solvers:ipopt_solver",
        "//solvers:mathematical_program",
        "//tools/performance:fixture_common",
        "//tools/performance:gflags_main",
    ],
    add_test_rule = True,
    test_rule_args = [
        # When testing, only run the smallest test.
        "--benchmark_filter=.*/10$$",
    ],
)

drake_py_experiment_binary(
    name = "ipopt_solver_experiment",
    googlebench_binary = ":benchmark_ipopt_solver",
)

drake_cc_library(
    name = "mpc_fixture",
    testonly = True,
    srcs = ["mpc_fixture.cc"],
    hdrs = ["mpc_fixture.h"],
    deps = [
        "//solvers:mathematical_program",
        "//tools/performance:fixture_common",
    ],
)

drake_cc_googlebench_binary(
    name = "benchmark_solver_cache",
    srcs = ["benchmark_solver_cache.cc"],
    deps = [
        ":mpc_fixture",
        "//common:add_text_logging_gflags",
        "//common:essential",
        "//solvers:osqp_solver",
        "//solvers:scs_solver",
        "//solvers:solver_cache_profiler",
        "//tools/performance:fixture_common",
        "//tools/performance:fixture_memory",
        "//tools/performance:gflags_main",
        "@gflags",
    ],
    add_test_rule = True,
    test_rule_args = [
        "--benchmark_filter=.*/50/1/0$$",
        "--benchmark_min_time=0.01s",
    ],
)

drake_cc_library(
    name = "native_mpc",
    testonly = True,
    hdrs = ["native_mpc.h"],
    deps = [
        ":mpc_fixture",
        "//tools/performance:fixture_memory",
    ],
)

drake_cc_googlebench_binary(
    name = "benchmark_native_osqp",
    srcs = ["benchmark_native_osqp.cc"],
    deps = [
        ":native_mpc",
        "//solvers:aggregate_costs_constraints",
        "//solvers:osqp_solver",
        "//tools/performance:gflags_main",
        "@osqp_internal//:osqp",
    ],
    add_test_rule = True,
    test_rule_args = ["--benchmark_filter=.*/50/2/[012]/1$$"],
)

add_lint_tests()
